# Generated by Django 4.2.13 on 2024-06-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subaccount_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='motif',
            field=models.CharField(choices=[('Sous compte assurance santé ', 'Sous compte assurance santé '), ('Sous compte commerce ', 'Sous compte commerce '), ('Sous compte assurance scolaire ', 'Sous compte assurance scolaire '), ('Sous compte agriculture', 'Sous compte agriculture')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='accounts.entreprise'),
        ),
    ]
