# Generated by Django 5.0.4 on 2024-07-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subaccount_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='motif',
            field=models.CharField(choices=[('Sous compte assurance scolaire ', 'Sous compte assurance scolaire '), ('Sous compte commerce ', 'Sous compte commerce '), ('Sous compte agriculture', 'Sous compte agriculture'), ('Sous compte assurance santé ', 'Sous compte assurance santé ')], max_length=50),
        ),
    ]
