# Generated by Django 4.2.13 on 2024-06-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_subaccount_motif_alter_user_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default=23, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='motif',
            field=models.CharField(choices=[('Sous compte agriculture', 'Sous compte agriculture'), ('Sous compte assurance scolaire ', 'Sous compte assurance scolaire '), ('Sous compte assurance santé ', 'Sous compte assurance santé '), ('Sous compte commerce ', 'Sous compte commerce ')], max_length=50),
        ),
    ]
