# Generated by Django 5.0.4 on 2024-07-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_subaccount_motif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAccount',
        ),
    ]
