# Generated by Django 4.2.13 on 2024-06-11 09:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subaccount_motif_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='motif',
            field=models.CharField(choices=[('Sous compte commerce ', 'Sous compte commerce '), ('Sous compte assurance santé ', 'Sous compte assurance santé '), ('Sous compte assurance scolaire ', 'Sous compte assurance scolaire '), ('Sous compte agriculture', 'Sous compte agriculture')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
