# Generated by Django 4.2.13 on 2024-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_subaccount_motif_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='motif',
            field=models.CharField(choices=[('Sous compte assurance scolaire ', 'Sous compte assurance scolaire '), ('Sous compte agriculture', 'Sous compte agriculture'), ('Sous compte commerce ', 'Sous compte commerce '), ('Sous compte assurance santé ', 'Sous compte assurance santé ')], max_length=50),
        ),
    ]
