# Generated by Django 4.2.13 on 2024-06-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_subaccount_motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='motif',
            field=models.CharField(choices=[('Sous compte commerce ', 'Sous compte commerce '), ('Sous compte assurance santé ', 'Sous compte assurance santé '), ('Sous compte agriculture', 'Sous compte agriculture'), ('Sous compte assurance scolaire ', 'Sous compte assurance scolaire ')], max_length=50),
        ),
    ]
