# Generated by Django 4.2.13 on 2024-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_username_alter_subaccount_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='motif',
            field=models.CharField(choices=[('Sous compte assurance scolaire ', 'Sous compte assurance scolaire '), ('Sous compte assurance santé ', 'Sous compte assurance santé '), ('Sous compte agriculture', 'Sous compte agriculture'), ('Sous compte commerce ', 'Sous compte commerce ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
