# Generated by Django 4.2.13 on 2024-07-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_subaccount'),
        ('accounts', '0009_alter_subaccount_motif_and_more'),
    ]

    operations = [
    ]
