# Generated by Django 5.0.4 on 2024-11-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
